services:
  tablemaster-mobile-web:
    image: ghcr.io/tablemasterproject/tablemaster-mobile-web:prod
    container_name: tablemaster-mobile-web
    restart: unless-stopped
    ports:
      - "8081:80"
