// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcFkbdegYPyZIYjeW7oZ4hGq8NqifLmQ',
    appId: '1:739801589159:web:621e5abd2da15b1bf60282',
    messagingSenderId: '739801589159',
    projectId: 'tablemaster-6e5d1',
    authDomain: 'tablemaster-6e5d1.firebaseapp.com',
    storageBucket: 'tablemaster-6e5d1.firebasestorage.app',
    measurementId: 'G-WPMKX8XZXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKp1_Xth8SyNlZeMG-7C_zYxsFm92t0ls',
    appId: '1:739801589159:android:51dd96a4c059c3d9f60282',
    messagingSenderId: '739801589159',
    projectId: 'tablemaster-6e5d1',
    storageBucket: 'tablemaster-6e5d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAKwd0mBYrkcbIS6zu7QpwXGCgu-tER4',
    appId: '1:739801589159:ios:a1dbcb6f345152ccf60282',
    messagingSenderId: '739801589159',
    projectId: 'tablemaster-6e5d1',
    storageBucket: 'tablemaster-6e5d1.firebasestorage.app',
    iosBundleId: 'com.tablemastermobile.tableMasterMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAAKwd0mBYrkcbIS6zu7QpwXGCgu-tER4',
    appId: '1:739801589159:ios:a1dbcb6f345152ccf60282',
    messagingSenderId: '739801589159',
    projectId: 'tablemaster-6e5d1',
    storageBucket: 'tablemaster-6e5d1.firebasestorage.app',
    iosBundleId: 'com.tablemastermobile.tableMasterMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdcFkbdegYPyZIYjeW7oZ4hGq8NqifLmQ',
    appId: '1:739801589159:web:46bffe4ec4da0f2ff60282',
    messagingSenderId: '739801589159',
    projectId: 'tablemaster-6e5d1',
    authDomain: 'tablemaster-6e5d1.firebaseapp.com',
    storageBucket: 'tablemaster-6e5d1.firebasestorage.app',
    measurementId: 'G-VGVJ04LQ6B',
  );
}
